import React from "react";
import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google'
import "./css/globals.css";
import { ThemeModeScript, ThemeProvider } from 'flowbite-react';
import customTheme from "@/utils/theme/custom-theme";

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
})

export const metadata: Metadata = {
  title: "TailwindAdmin - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {typeof window !== "undefined" && <ThemeModeScript />}
      </head>
      <body className={`${dmSans.className}`}>
        <ThemeProvider theme={customTheme}>
          {children}
        </ThemeProvider>
      </body>
    </html>

  );
}
